services:
  db:
    image: postgres:16
    container_name: manverse_db
    restart: always
    environment:
      POSTGRES_DB: manverse_db
      POSTGRES_USER: manverse_user
      POSTGRES_PASSWORD: Manverse@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: manverse_redis
    restart: always

  backend:
    build: ./backend
    container_name: manverse_backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: manverse_db
      DB_USER: manverse_user
      DB_PASSWORD: Manverse@123
      REDIS_URL: redis://redis:6379/1
    volumes:
      - /home/manverse/static:/app/config/staticfiles
      - /home/manverse/media:/app/config/media
  frontend:
    build: ./frontend/frontend
    container_name: manverse_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
