 
services:
  db:
    image: postgres:16
    container_name: manverse_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: manverse_redis
    restart: always

  backend:
    build: ./backend
    container_name: manverse_backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: redis://redis:6379/1
    volumes:
      - /home/manverse/static:/app/config/staticfiles
      - /home/manverse/media:/app/config/media

  frontend:
    build:
      context: ./frontend/frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: manverse_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BACKEND_URL: http://backend:8000
       

volumes:
  postgres_data: